deployment:
  tasks:
    - export DEPLOYPATH=/home/royq1172/public_html
    - cd /home/royq1172/repositories/undanganbaru
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /bin/cp -R dist/* $DEPLOYPATH/
